[tool.poetry]
name = "flask-peewee-restful"
version = "1.0.9"
description = "Generate Flask Restful API from Peewee Models"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
peewee = "^3.14.4"
Flask = "^2.0.2"
requests = "^2.26.0"
loguru = "^0.5.3"
typing_extensions = "^4.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
